package cc.cosmetica.include.twelvemonkeys.imageio.metadata.tiff;

public interface TIFF {
   short BYTE_ORDER_MARK_BIG_ENDIAN = 19789;
   short BYTE_ORDER_MARK_LITTLE_ENDIAN = 18761;
   int TIFF_MAGIC = 42;
   int BIGTIFF_MAGIC = 43;
   short TYPE_BYTE = 1;
   short TYPE_ASCII = 2;
   short TYPE_SHORT = 3;
   short TYPE_LONG = 4;
   short TYPE_RATIONAL = 5;
   short TYPE_SBYTE = 6;
   short TYPE_UNDEFINED = 7;
   short TYPE_SSHORT = 8;
   short TYPE_SLONG = 9;
   short TYPE_SRATIONAL = 10;
   short TYPE_FLOAT = 11;
   short TYPE_DOUBLE = 12;
   short TYPE_IFD = 13;
   short TYPE_LONG8 = 16;
   short TYPE_SLONG8 = 17;
   short TYPE_IFD8 = 18;
   String[] TYPE_NAMES = new String[]{
      null,
      "BYTE",
      "ASCII",
      "SHORT",
      "LONG",
      "RATIONAL",
      "SBYTE",
      "UNDEFINED",
      "SSHORT",
      "SLONG",
      "SRATIONAL",
      "FLOAT",
      "DOUBLE",
      "IFD",
      null,
      null,
      "LONG8",
      "SLONG8",
      "IFD8"
   };
   int[] TYPE_LENGTHS = new int[]{-1, 1, 1, 2, 4, 8, 1, 1, 2, 4, 8, 4, 8, 4, -1, -1, 8, 8, 8};
   int TAG_EXIF_IFD = 34665;
   int TAG_GPS_IFD = 34853;
   int TAG_INTEROP_IFD = 40965;
   int TAG_IMAGE_WIDTH = 256;
   int TAG_IMAGE_HEIGHT = 257;
   int TAG_BITS_PER_SAMPLE = 258;
   int TAG_COMPRESSION = 259;
   int TAG_PHOTOMETRIC_INTERPRETATION = 262;
   int TAG_FILL_ORDER = 266;
   int TAG_ORIENTATION = 274;
   int TAG_SAMPLES_PER_PIXEL = 277;
   int TAG_PLANAR_CONFIGURATION = 284;
   int TAG_SAMPLE_FORMAT = 339;
   int TAG_YCBCR_SUB_SAMPLING = 530;
   int TAG_YCBCR_POSITIONING = 531;
   int TAG_X_RESOLUTION = 282;
   int TAG_Y_RESOLUTION = 283;
   int TAG_X_POSITION = 286;
   int TAG_Y_POSITION = 287;
   int TAG_RESOLUTION_UNIT = 296;
   int TAG_STRIP_OFFSETS = 273;
   int TAG_ROWS_PER_STRIP = 278;
   int TAG_STRIP_BYTE_COUNTS = 279;
   int TAG_FREE_OFFSETS = 288;
   int TAG_FREE_BYTE_COUNTS = 289;
   int TAG_JPEG_INTERCHANGE_FORMAT = 513;
   int TAG_JPEG_INTERCHANGE_FORMAT_LENGTH = 514;
   int TAG_GROUP3OPTIONS = 292;
   int TAG_GROUP4OPTIONS = 293;
   int TAG_TRANSFER_FUNCTION = 301;
   int TAG_PREDICTOR = 317;
   int TAG_WHITE_POINT = 318;
   int TAG_PRIMARY_CHROMATICITIES = 319;
   int TAG_COLOR_MAP = 320;
   int TAG_INK_SET = 332;
   int TAG_INK_NAMES = 333;
   int TAG_NUMBER_OF_INKS = 334;
   int TAG_EXTRA_SAMPLES = 338;
   int TAG_TRANSFER_RANGE = 342;
   int TAG_YCBCR_COEFFICIENTS = 529;
   int TAG_REFERENCE_BLACK_WHITE = 532;
   int TAG_DATE_TIME = 306;
   int TAG_DOCUMENT_NAME = 269;
   int TAG_IMAGE_DESCRIPTION = 270;
   int TAG_MAKE = 271;
   int TAG_MODEL = 272;
   int TAG_PAGE_NAME = 285;
   int TAG_PAGE_NUMBER = 297;
   int TAG_SOFTWARE = 305;
   int TAG_ARTIST = 315;
   int TAG_HOST_COMPUTER = 316;
   int TAG_COPYRIGHT = 33432;
   int TAG_SUBFILE_TYPE = 254;
   int TAG_OLD_SUBFILE_TYPE = 255;
   int TAG_SUB_IFD = 330;
   int TAG_XMP = 700;
   int TAG_IPTC = 33723;
   int TAG_PHOTOSHOP = 34377;
   int TAG_PHOTOSHOP_IMAGE_SOURCE_DATA = 37724;
   int TAG_PHOTOSHOP_ANNOTATIONS = 50255;
   int TAG_ICC_PROFILE = 34675;
   int TAG_MODI_BLC = 34718;
   int TAG_MODI_VECTOR = 34719;
   int TAG_MODI_PTC = 34720;
   int TAG_MODI_PLAIN_TEXT = 37679;
   int TAG_MODI_OLE_PROPERTY_SET = 37680;
   int TAG_MODI_TEXT_POS_INFO = 37681;
   int TAG_TILE_WIDTH = 322;
   int TAG_TILE_HEIGTH = 323;
   int TAG_TILE_OFFSETS = 324;
   int TAG_TILE_BYTE_COUNTS = 325;
   int TAG_JPEG_TABLES = 347;
   int TAG_OLD_JPEG_PROC = 512;
   int TAG_OLD_JPEG_Q_TABLES = 519;
   int TAG_OLD_JPEG_DC_TABLES = 520;
   int TAG_OLD_JPEG_AC_TABLES = 521;
}
