modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="ends_delight"
version="2.6.1+neoforge.1.21.1"
displayName="End's Delight"
logoFile="logo.png"
logoBlur=false
credits="GamingeckeSpace, Lobster0228, mpustovoi, PExPE3, Roby1164, SABITRON, tankplanelaserkoala, TheLegendofSaram, unroman and many others!"
authors="FoggyHillside"
description='''An addon mod for Farmer's Delight based around adding culinary content to the End!'''

[[dependencies.ends_delight]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.219,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ends_delight]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ends_delight]]
    modId="farmersdelight"
    type="required"
    versionRange="[1.3.1,)"
    ordering="NONE"
    side="BOTH"
