modLoader="javafml" #mandatory
loaderVersion="[4,)" #mandatory
license="CC BY-NC-ND 4.0"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]] #mandatory
modId="cristellib" #mandatory
version="3.1.7" #mandatory

displayName="Cristel Lib"
authors="Cristelknight"
displayURL="https://modrinth.com/mod/cristel-lib"
logoFile="pack.png"


# Display Test controls the display for your mod in the server connection screen
# MATCH_VERSION means that your mod will cause a red X if the versions on client and server differ. This is the default behaviour and should be what you choose if you have server and client elements to your mod.
# IGNORE_SERVER_VERSION means that your mod will not cause a red X if it's present on the server but not on the client. This is what you should use if you're a server only mod.
# IGNORE_ALL_VERSION means that your mod will not cause a red X if it's present on the client or the server. This is a special case and should only be used if your mod has no server component.
# NONE means that no display test is set on your mod. You need to do this yourself, see IExtensionPoint.DisplayTest for more information. You can define any scheme you wish with this value.
# IMPORTANT NOTE: this is NOT an instruction as to which environments (CLIENT or DEDICATED SERVER) your mod loads on. Your mod should load (and maybe do nothing!) whereever it finds itself.
displayTest="IGNORE_ALL_VERSION"

description= '''A Library mod for easy structure config and runtime datapacks.'''

[[mixins]]
config="cristellib-common.mixins.json"

[[dependencies.cristellib]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.cristellib]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.cristellib]]
modId="t_and_t"
type="incompatible"
versionRange="(,1.13.3]"
ordering="NONE"
side="BOTH"

[[dependencies.cristellib]]
modId="expanded_ecosphere"
type="incompatible"
versionRange="[0,3.4.3]"
ordering="NONE"
side="BOTH"
