modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="tanshugetrees"
version="1.8.0"
displayName="Tan's Huge Trees"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/tans-huge-trees"
logoFile="logo.png"
credits="Created with MCreator and IntelliJ"
authors="TannyJung"
description="Generate trees and some nature stuffs around the world. With some detailed systems."

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.tanshugetrees]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.tanshugetrees]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration