package com.mcwbridges.kikoz.init;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.ItemLike;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class TabInit {
   public static final DeferredRegister<CreativeModeTab> CREATIVE_TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, "mcwbridges");
   public static final DeferredHolder<CreativeModeTab, CreativeModeTab> BRIDGEITEMGROUP = CREATIVE_TABS.register(
      "mcwbridges",
      () -> CreativeModeTab.builder()
         .title(Component.translatable("itemGroup.mcwbridges"))
         .icon(() -> new ItemStack((ItemLike)BlockInit.IRON_BRIDGE.get()))
         .displayItems((enabledFeatures, entries) -> {
            entries.accept((ItemLike)ItemInit.PLIERS.get());
            entries.accept((ItemLike)BlockInit.BRIDGE_TORCH.get());
            entries.accept((ItemLike)BlockInit.BRIDGE_LANTERN.get());
            entries.accept((ItemLike)BlockInit.IRON_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.OAK_LOG_BRIDGE_MIDDLE.get());
            entries.accept((ItemLike)BlockInit.BIRCH_LOG_BRIDGE_MIDDLE.get());
            entries.accept((ItemLike)BlockInit.ACACIA_LOG_BRIDGE_MIDDLE.get());
            entries.accept((ItemLike)BlockInit.SPRUCE_LOG_BRIDGE_MIDDLE.get());
            entries.accept((ItemLike)BlockInit.JUNGLE_LOG_BRIDGE_MIDDLE.get());
            entries.accept((ItemLike)BlockInit.DARK_OAK_LOG_BRIDGE_MIDDLE.get());
            entries.accept((ItemLike)BlockInit.CRIMSON_LOG_BRIDGE_MIDDLE.get());
            entries.accept((ItemLike)BlockInit.WARPED_LOG_BRIDGE_MIDDLE.get());
            entries.accept((ItemLike)BlockInit.MANGROVE_LOG_BRIDGE_MIDDLE.get());
            entries.accept((ItemLike)BlockInit.CHERRY_LOG_BRIDGE_MIDDLE.get());
            entries.accept((ItemLike)BlockInit.ROPE_OAK_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.ROPE_BIRCH_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.ROPE_SPRUCE_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.ROPE_JUNGLE_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.ROPE_ACACIA_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.ROPE_DARK_OAK_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.ROPE_CRIMSON_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.ROPE_WARPED_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.ROPE_MANGROVE_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.ROPE_CHERRY_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.BRICK_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.SANDSTONE_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.STONE_BRICK_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.ORANGE_SANDSTONE_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.BLACKSTONE_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.MOSSY_STONE_BRICK_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.DEEPSLATE_BRICK_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.DEEPSLATE_TILE_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.MUD_BRICK_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.COBBLESTONE_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.MOSSY_COBBLESTONE_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.ANDESITE_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.GRANITE_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.DIORITE_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.PRISMARINE_BRICKS_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.NETHER_BRICKS_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.END_STONE_BRICKS_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.OAK_RAIL_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.SPRUCE_RAIL_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.BIRCH_RAIL_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.JUNGLE_RAIL_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.ACACIA_RAIL_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.DARK_OAK_RAIL_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.CRIMSON_RAIL_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.WARPED_RAIL_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.MANGROVE_RAIL_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.CHERRY_RAIL_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.BAMBOO_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.DRY_BAMBOO_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.ASIAN_RED_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.GLASS_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.BALUSTRADE_STONE_BRICKS_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.BALUSTRADE_SANDSTONE_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.BALUSTRADE_BRICKS_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.BALUSTRADE_ORANGE_SANDSTONE_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.BALUSTRADE_BLACKSTONE_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.BALUSTRADE_MOSSY_STONE_BRICKS_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.BALUSTRADE_DEEPSLATE_BRICKS_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.BALUSTRADE_DEEPSLATE_TILES_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.BALUSTRADE_MUD_BRICKS_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.BALUSTRADE_COBBLESTONE_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.BALUSTRADE_MOSSY_COBBLESTONE_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.BALUSTRADE_ANDESITE_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.BALUSTRADE_GRANITE_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.BALUSTRADE_DIORITE_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.BALUSTRADE_PRISMARINE_BRICKS_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.BALUSTRADE_NETHER_BRICKS_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.BALUSTRADE_END_STONE_BRICKS_BRIDGE.get());
            entries.accept((ItemLike)BlockInit.IRON_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.OAK_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.SPRUCE_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.BIRCH_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.JUNGLE_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.ACACIA_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.DARK_OAK_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.CRIMSON_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.WARPED_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.MANGROVE_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.CHERRY_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.ASIAN_RED_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.GLASS_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.BRICK_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.SANDSTONE_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.STONE_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.RED_SANDSTONE_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.BLACKSTONE_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.MOSSY_STONE_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.DEEPSLATE_BRICK_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.DEEPSLATE_TILE_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.MUD_BRICK_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.BAMBOO_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.DRY_BAMBOO_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.COBBLESTONE_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.MOSSY_COBBLESTONE_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.ANDESITE_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.GRANITE_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.DIORITE_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.PRISMARINE_BRICKS_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.NETHER_BRICKS_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.END_STONE_BRICKS_BRIDGE_PIER.get());
            entries.accept((ItemLike)BlockInit.IRON_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.OAK_LOG_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.SPRUCE_LOG_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.BIRCH_LOG_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.JUNGLE_LOG_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.ACACIA_LOG_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.DARK_OAK_LOG_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.CRIMSON_LOG_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.WARPED_LOG_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.MANGROVE_LOG_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.CHERRY_LOG_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.OAK_ROPE_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.SPRUCE_ROPE_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.BIRCH_ROPE_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.JUNGLE_ROPE_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.ACACIA_ROPE_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.DARK_OAK_ROPE_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.CRIMSON_ROPE_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.WARPED_ROPE_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.MANGROVE_ROPE_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.CHERRY_ROPE_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.STONE_BRICK_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.SANDSTONE_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.ASIAN_RED_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.GLASS_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.BRICK_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.RED_SANDSTONE_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.BLACKSTONE_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.MOSSY_STONE_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.DEEPSLATE_BRICK_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.DEEPSLATE_TILE_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.MUD_BRICK_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.BAMBOO_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.DRY_BAMBOO_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.COBBLESTONE_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.MOSSY_COBBLESTONE_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.ANDESITE_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.GRANITE_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.DIORITE_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.PRISMARINE_BRICKS_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.NETHER_BRICKS_BRIDGE_STAIR.get());
            entries.accept((ItemLike)BlockInit.END_STONE_BRICKS_BRIDGE_STAIR.get());
         })
         .build()
   );
}
