modLoader="lowcodefml"
loaderVersion="[1,)"
license="Stardust Labs License"
issueTrackerURL="https://github.com/Stardust-Labs-MC/Nullscape/issues"

[[mods]]
    modId="nullscape"
    version="1.2.14"
    displayName="Nullscape"
    displayURL="https://www.stardustlabs.net/"
    logoFile="pack.png"
    authors="Stardust Labs"
    credits="Starmute: Owner. catter1: Maintainer."
    description="Transforms the boring Vanilla end into an alien dimension with the most surreal terrain imaginable. Topped with a couple of new biomes to add to the experience, whilst keeping the end desolate."

[[dependencies.nullscape]]
    modId="forge"
    mandatory=false
    versionRange="[51,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nullscape]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"