modLoader="javafml"
loaderVersion="[2,)"
authors="Luck"
license="GPLv3"

[[mods]]
modId="spark"
displayName="spark"
version="1.10.124"
description="spark is a performance profiling plugin/mod for Minecraft clients, servers and proxies."

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.spark]]
modId = "neoforge"
mandatory=true
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"