modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/FinnSetchell/MoogsStructureLib/issues" #optional
license="https://github.com/FinnSetchell/MoogsStructureLib/blob/1.21.5/LICENSE"

[[mods]]
    modId="moogs_structures"
    logoFile= "assets/moogs_structures/icon.png"
    logoBlur=false
    version="3.1.1"
    displayName="Moog's Structure Lib"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/moogs-structure-lib"
    authors="FinnDog"
    credits="Thanks to TelepathicGrunt for their structure mod template and rs"
    description='''
    Moogs Structure Lib is a library mod used to generate the structures from the
    moog structure mods. Feel free to use it for your own projects and mods.
    '''

[[mixins]]
    config = "moogs_structures-neoforge.mixins.json"

[[mixins]]
    config = "moogs_structures-common.mixins.json"

[[dependencies.moogs_structures]]
    modId="minecraft"
    mandatory = true
versionRange="[1.21,1.21.2)"
    ordering = "NONE"
    side = "BOTH"