modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Cosmetica-cc/Cosmetica-2/issues"
license = "Apache 2.0"

[[mods]]
modId = "cosmetica"
version = "2.0.1-1.21.1"
displayName = "Cosmetica"
authors = "Valoeghese, Eyezah"
description = '''
Custom Cosmetics for Free, Forever.
'''
logoFile = "assets/cosmetica/icon.png"

[[dependencies.cosmetica]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cosmetica]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.4)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "cosmetica-common.mixins.json"

[[mixins]]
config = "cosmetica-neoforge.mixins.json"

