package com.mcwlights.kikoz.init;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.ItemLike;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class TabInit {
   public static DeferredRegister<CreativeModeTab> CREATIVE_TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, "mcwlights");
   public static final DeferredHolder<CreativeModeTab, CreativeModeTab> LIGHTSITEMGROUP = CREATIVE_TABS.register(
      "mcwlights",
      () -> CreativeModeTab.builder()
         .title(Component.translatable("itemGroup.mcwlights"))
         .icon(() -> new ItemStack((ItemLike)BlockInit.BLUE_LAMP.get()))
         .displayItems((enabledFeatures, entries) -> {
            entries.accept((ItemLike)BlockInit.WHITE_LAMP.get());
            entries.accept((ItemLike)BlockInit.ORANGE_LAMP.get());
            entries.accept((ItemLike)BlockInit.MAGENTA_LAMP.get());
            entries.accept((ItemLike)BlockInit.LIGHT_BLUE_LAMP.get());
            entries.accept((ItemLike)BlockInit.YELLOW_LAMP.get());
            entries.accept((ItemLike)BlockInit.LIME_LAMP.get());
            entries.accept((ItemLike)BlockInit.PINK_LAMP.get());
            entries.accept((ItemLike)BlockInit.GRAY_LAMP.get());
            entries.accept((ItemLike)BlockInit.LIGHT_GRAY_LAMP.get());
            entries.accept((ItemLike)BlockInit.CYAN_LAMP.get());
            entries.accept((ItemLike)BlockInit.PURPLE_LAMP.get());
            entries.accept((ItemLike)BlockInit.BLUE_LAMP.get());
            entries.accept((ItemLike)BlockInit.BROWN_LAMP.get());
            entries.accept((ItemLike)BlockInit.GREEN_LAMP.get());
            entries.accept((ItemLike)BlockInit.RED_LAMP.get());
            entries.accept((ItemLike)BlockInit.BLACK_LAMP.get());
            entries.accept((ItemLike)BlockInit.OAK_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.SPRUCE_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.BIRCH_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.JUNGLE_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.ACACIA_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.DARK_OAK_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.CRIMSON_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.WARPED_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.MANGROVE_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.BAMBOO_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.CHERRY_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.SOUL_OAK_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.SOUL_SPRUCE_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.SOUL_BIRCH_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.SOUL_JUNGLE_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.SOUL_ACACIA_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.SOUL_DARK_OAK_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.SOUL_CRIMSON_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.SOUL_WARPED_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.SOUL_MANGROVE_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.SOUL_BAMBOO_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.SOUL_CHERRY_TIKI_TORCH.get());
            entries.accept((ItemLike)BlockInit.WHITE_CEILING_LIGHT.get());
            entries.accept((ItemLike)BlockInit.ORANGE_CEILING_LIGHT.get());
            entries.accept((ItemLike)BlockInit.MAGENTA_CEILING_LIGHT.get());
            entries.accept((ItemLike)BlockInit.LIGHT_BLUE_CEILING_LIGHT.get());
            entries.accept((ItemLike)BlockInit.YELLOW_CEILING_LIGHT.get());
            entries.accept((ItemLike)BlockInit.LIME_CEILING_LIGHT.get());
            entries.accept((ItemLike)BlockInit.PINK_CEILING_LIGHT.get());
            entries.accept((ItemLike)BlockInit.GRAY_CEILING_LIGHT.get());
            entries.accept((ItemLike)BlockInit.LIGHT_GRAY_CEILING_LIGHT.get());
            entries.accept((ItemLike)BlockInit.CYAN_CEILING_LIGHT.get());
            entries.accept((ItemLike)BlockInit.PURPLE_CEILING_LIGHT.get());
            entries.accept((ItemLike)BlockInit.BLUE_CEILING_LIGHT.get());
            entries.accept((ItemLike)BlockInit.BROWN_CEILING_LIGHT.get());
            entries.accept((ItemLike)BlockInit.GREEN_CEILING_LIGHT.get());
            entries.accept((ItemLike)BlockInit.RED_CEILING_LIGHT.get());
            entries.accept((ItemLike)BlockInit.BLACK_CEILING_LIGHT.get());
            entries.accept((ItemLike)BlockInit.CLASSIC_STREET_LAMP.get());
            entries.accept((ItemLike)BlockInit.DOUBLE_STREET_LAMP.get());
            entries.accept((ItemLike)BlockInit.SOUL_CLASSIC_STREET_LAMP.get());
            entries.accept((ItemLike)BlockInit.SOUL_DOUBLE_STREET_LAMP.get());
            entries.accept((ItemLike)BlockInit.LAVA_LAMP.get());
            entries.accept((ItemLike)BlockInit.GARDEN_LIGHT.get());
            entries.accept((ItemLike)BlockInit.THIN_GARDEN_LIGHT.get());
            entries.accept((ItemLike)BlockInit.TOWER_GARDEN_LIGHT.get());
            entries.accept((ItemLike)BlockInit.COVERED_GARDEN_LIGHT.get());
            entries.accept((ItemLike)BlockInit.STRIPED_GARDEN_LIGHT.get());
            entries.accept((ItemLike)BlockInit.ROUND_GARDEN_LIGHT.get());
            entries.accept((ItemLike)BlockInit.WHITE_PAPER_LAMP.get());
            entries.accept((ItemLike)BlockInit.LIGHT_GRAY_PAPER_LAMP.get());
            entries.accept((ItemLike)BlockInit.GRAY_PAPER_LAMP.get());
            entries.accept((ItemLike)BlockInit.BLACK_PAPER_LAMP.get());
            entries.accept((ItemLike)BlockInit.BROWN_PAPER_LAMP.get());
            entries.accept((ItemLike)BlockInit.RED_PAPER_LAMP.get());
            entries.accept((ItemLike)BlockInit.ORANGE_PAPER_LAMP.get());
            entries.accept((ItemLike)BlockInit.YELLOW_PAPER_LAMP.get());
            entries.accept((ItemLike)BlockInit.LIME_PAPER_LAMP.get());
            entries.accept((ItemLike)BlockInit.GREEN_PAPER_LAMP.get());
            entries.accept((ItemLike)BlockInit.CYAN_PAPER_LAMP.get());
            entries.accept((ItemLike)BlockInit.LIGHT_BLUE_PAPER_LAMP.get());
            entries.accept((ItemLike)BlockInit.BLUE_PAPER_LAMP.get());
            entries.accept((ItemLike)BlockInit.PURPLE_PAPER_LAMP.get());
            entries.accept((ItemLike)BlockInit.MAGENTA_PAPER_LAMP.get());
            entries.accept((ItemLike)BlockInit.PINK_PAPER_LAMP.get());
            entries.accept((ItemLike)BlockInit.STRIPED_LANTERN.get());
            entries.accept((ItemLike)BlockInit.COVERED_LANTERN.get());
            entries.accept((ItemLike)BlockInit.CHAIN_LANTERN.get());
            entries.accept((ItemLike)BlockInit.TAVERN_LANTERN.get());
            entries.accept((ItemLike)BlockInit.FESTIVE_LANTERN.get());
            entries.accept((ItemLike)BlockInit.CROSS_LANTERN.get());
            entries.accept((ItemLike)BlockInit.BELL_LANTERN.get());
            entries.accept((ItemLike)BlockInit.WALL_LANTERN.get());
            entries.accept((ItemLike)BlockInit.STRIPED_WALL_LANTERN.get());
            entries.accept((ItemLike)BlockInit.COVERED_WALL_LANTERN.get());
            entries.accept((ItemLike)BlockInit.CHAIN_WALL_LANTERN.get());
            entries.accept((ItemLike)BlockInit.TAVERN_WALL_LANTERN.get());
            entries.accept((ItemLike)BlockInit.FESTIVE_WALL_LANTERN.get());
            entries.accept((ItemLike)BlockInit.CROSS_WALL_LANTERN.get());
            entries.accept((ItemLike)BlockInit.BELL_WALL_LANTERN.get());
            entries.accept((ItemLike)BlockInit.WALL_LAMP.get());
            entries.accept((ItemLike)BlockInit.SQUARE_WALL_LAMP.get());
            entries.accept((ItemLike)BlockInit.FRAMED_TORCH.get());
            entries.accept((ItemLike)BlockInit.IRON_FRAMED_TORCH.get());
            entries.accept((ItemLike)BlockInit.REINFORCED_TORCH.get());
            entries.accept((ItemLike)BlockInit.RUSTIC_TORCH.get());
            entries.accept((ItemLike)BlockInit.UPGRADED_TORCH.get());
            entries.accept((ItemLike)BlockInit.REDSTONE_LAMP_SLAB.get());
            entries.accept((ItemLike)BlockInit.GLOWSTONE_SLAB.get());
            entries.accept((ItemLike)BlockInit.SHROOMLIGHT_SLAB.get());
            entries.accept((ItemLike)BlockInit.SEA_LANTERN_SLAB.get());
            entries.accept((ItemLike)BlockInit.OAK_CEILING_FAN_LIGHT.get());
            entries.accept((ItemLike)BlockInit.SPRUCE_CEILING_FAN_LIGHT.get());
            entries.accept((ItemLike)BlockInit.BIRCH_CEILING_FAN_LIGHT.get());
            entries.accept((ItemLike)BlockInit.JUNGLE_CEILING_FAN_LIGHT.get());
            entries.accept((ItemLike)BlockInit.ACACIA_CEILING_FAN_LIGHT.get());
            entries.accept((ItemLike)BlockInit.DARK_OAK_CEILING_FAN_LIGHT.get());
            entries.accept((ItemLike)BlockInit.CRIMSON_CEILING_FAN_LIGHT.get());
            entries.accept((ItemLike)BlockInit.WARPED_CEILING_FAN_LIGHT.get());
            entries.accept((ItemLike)BlockInit.MANGROVE_CEILING_FAN_LIGHT.get());
            entries.accept((ItemLike)BlockInit.CHERRY_CEILING_FAN_LIGHT.get());
            entries.accept((ItemLike)BlockInit.GOLDEN_LOW_CANDLE_HOLDER.get());
            entries.accept((ItemLike)BlockInit.GOLDEN_CANDLE_HOLDER.get());
            entries.accept((ItemLike)BlockInit.GOLDEN_WALL_CANDLE_HOLDER.get());
            entries.accept((ItemLike)BlockInit.GOLDEN_DOUBLE_CANDLE_HOLDER.get());
            entries.accept((ItemLike)BlockInit.GOLDEN_TRIPLE_CANDLE_HOLDER.get());
            entries.accept((ItemLike)BlockInit.GOLDEN_SMALL_CHANDELIER.get());
            entries.accept((ItemLike)BlockInit.GOLDEN_CHANDELIER.get());
            entries.accept((ItemLike)BlockInit.COPPER_LOW_CANDLE_HOLDER.get());
            entries.accept((ItemLike)BlockInit.COPPER_CANDLE_HOLDER.get());
            entries.accept((ItemLike)BlockInit.COPPER_WALL_CANDLE_HOLDER.get());
            entries.accept((ItemLike)BlockInit.COPPER_DOUBLE_CANDLE_HOLDER.get());
            entries.accept((ItemLike)BlockInit.COPPER_TRIPLE_CANDLE_HOLDER.get());
            entries.accept((ItemLike)BlockInit.COPPER_SMALL_CHANDELIER.get());
            entries.accept((ItemLike)BlockInit.COPPER_CHANDELIER.get());
            entries.accept((ItemLike)BlockInit.IRON_LOW_CANDLE_HOLDER.get());
            entries.accept((ItemLike)BlockInit.IRON_CANDLE_HOLDER.get());
            entries.accept((ItemLike)BlockInit.IRON_WALL_CANDLE_HOLDER.get());
            entries.accept((ItemLike)BlockInit.IRON_DOUBLE_CANDLE_HOLDER.get());
            entries.accept((ItemLike)BlockInit.IRON_TRIPLE_CANDLE_HOLDER.get());
            entries.accept((ItemLike)BlockInit.IRON_SMALL_CHANDELIER.get());
            entries.accept((ItemLike)BlockInit.IRON_CHANDELIER.get());
            entries.accept((ItemLike)BlockInit.GOLDEN_CHAIN.get());
            entries.accept((ItemLike)BlockInit.COPPER_CHAIN.get());
         })
         .build()
   );
}
