@ParametersAreNonnullByDefault
@FieldsAndMethodsAreNonnullByDefault
package mezz.jei.neoforge.startup;

import javax.annotation.ParametersAreNonnullByDefault;
import mezz.jei.common.FieldsAndMethodsAreNonnullByDefault;
