package net.mcreator.undeadrevamp.init;

import net.mcreator.undeadrevamp.block.AltaractiveBlock;
import net.mcreator.undeadrevamp.block.AltarnomBlock;
import net.mcreator.undeadrevamp.block.ArapholiaBlock;
import net.mcreator.undeadrevamp.block.BasaltechesteBlock;
import net.mcreator.undeadrevamp.block.BirchinducerBlock;
import net.mcreator.undeadrevamp.block.BlacpetalblockBlock;
import net.mcreator.undeadrevamp.block.BlockofbostroxBlock;
import net.mcreator.undeadrevamp.block.BostrokestoneBlock;
import net.mcreator.undeadrevamp.block.BostroxoreBlock;
import net.mcreator.undeadrevamp.block.BostroxslabsBlock;
import net.mcreator.undeadrevamp.block.BostroxstairsBlock;
import net.mcreator.undeadrevamp.block.BostroxwallBlock;
import net.mcreator.undeadrevamp.block.CherryblossominducerBlock;
import net.mcreator.undeadrevamp.block.ChiseledDripstonepillarBlock;
import net.mcreator.undeadrevamp.block.ChiseleddripstoneblockBlock;
import net.mcreator.undeadrevamp.block.ChiseleddripstonepillarbottomBlock;
import net.mcreator.undeadrevamp.block.ChiseleddripstonepillartopBlock;
import net.mcreator.undeadrevamp.block.CobbledbostroxslabBlock;
import net.mcreator.undeadrevamp.block.CobbledbostroxstairsBlock;
import net.mcreator.undeadrevamp.block.CobbledbostroxwallBlock;
import net.mcreator.undeadrevamp.block.Coffinbreadstage2Block;
import net.mcreator.undeadrevamp.block.Coffinbreadstage3Block;
import net.mcreator.undeadrevamp.block.Coffinbreadstage4Block;
import net.mcreator.undeadrevamp.block.CoffinbroadBlock;
import net.mcreator.undeadrevamp.block.DarkoakinducerBlock;
import net.mcreator.undeadrevamp.block.DarkoakinducerinactiveBlock;
import net.mcreator.undeadrevamp.block.DeepslateinducerBlock;
import net.mcreator.undeadrevamp.block.DeepslateinducerinactiveBlock;
import net.mcreator.undeadrevamp.block.InducerstoneBlock;
import net.mcreator.undeadrevamp.block.InducerstoneinactiveBlock;
import net.mcreator.undeadrevamp.block.JungleinducerBlock;
import net.mcreator.undeadrevamp.block.MangroveinducerBlock;
import net.mcreator.undeadrevamp.block.OakinducerBlock;
import net.mcreator.undeadrevamp.block.OakinducerinactiveBlock;
import net.mcreator.undeadrevamp.block.RareimmortalsummonblockBlock;
import net.mcreator.undeadrevamp.block.SavannainducerBlock;
import net.mcreator.undeadrevamp.block.SomnolencespawnsBlock;
import net.mcreator.undeadrevamp.block.SpurceinducerBlock;
import net.mcreator.undeadrevamp.block.WoodennestBlock;
import net.mcreator.undeadrevamp.block.Woodennestharvest1Block;
import net.mcreator.undeadrevamp.block.Woodennestharvest2Block;
import net.mcreator.undeadrevamp.block.Woodennestharvest3Block;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredRegister.Blocks;

public class UndeadRevamp2ModBlocks {
   public static final Blocks REGISTRY = DeferredRegister.createBlocks("undead_revamp2");
   public static final DeferredBlock<Block> ARAPHOLIA = REGISTRY.register("arapholia", ArapholiaBlock::new);
   public static final DeferredBlock<Block> BOSTROXORE = REGISTRY.register("bostroxore", BostroxoreBlock::new);
   public static final DeferredBlock<Block> BOSTROKESTONE = REGISTRY.register("bostrokestone", BostrokestoneBlock::new);
   public static final DeferredBlock<Block> BLOCKOFBOSTROX = REGISTRY.register("blockofbostrox", BlockofbostroxBlock::new);
   public static final DeferredBlock<Block> BLACPETALBLOCK = REGISTRY.register("blacpetalblock", BlacpetalblockBlock::new);
   public static final DeferredBlock<Block> RAREIMMORTALSUMMONBLOCK = REGISTRY.register("rareimmortalsummonblock", RareimmortalsummonblockBlock::new);
   public static final DeferredBlock<Block> BOSTROXWALL = REGISTRY.register("bostroxwall", BostroxwallBlock::new);
   public static final DeferredBlock<Block> BOSTROXSTAIRS = REGISTRY.register("bostroxstairs", BostroxstairsBlock::new);
   public static final DeferredBlock<Block> COBBLEDBOSTROXWALL = REGISTRY.register("cobbledbostroxwall", CobbledbostroxwallBlock::new);
   public static final DeferredBlock<Block> COBBLEDBOSTROXSTAIRS = REGISTRY.register("cobbledbostroxstairs", CobbledbostroxstairsBlock::new);
   public static final DeferredBlock<Block> BOSTROXSLABS = REGISTRY.register("bostroxslabs", BostroxslabsBlock::new);
   public static final DeferredBlock<Block> COBBLEDBOSTROXSLAB = REGISTRY.register("cobbledbostroxslab", CobbledbostroxslabBlock::new);
   public static final DeferredBlock<Block> WOODENNEST = REGISTRY.register("woodennest", WoodennestBlock::new);
   public static final DeferredBlock<Block> WOODENNESTHARVEST_1 = REGISTRY.register("woodennestharvest_1", Woodennestharvest1Block::new);
   public static final DeferredBlock<Block> WOODENNESTHARVEST_2 = REGISTRY.register("woodennestharvest_2", Woodennestharvest2Block::new);
   public static final DeferredBlock<Block> WOODENNESTHARVEST_3 = REGISTRY.register("woodennestharvest_3", Woodennestharvest3Block::new);
   public static final DeferredBlock<Block> CHISELED_DRIPSTONEPILLAR = REGISTRY.register("chiseled_dripstonepillar", ChiseledDripstonepillarBlock::new);
   public static final DeferredBlock<Block> CHISELEDDRIPSTONEPILLARTOP = REGISTRY.register("chiseleddripstonepillartop", ChiseleddripstonepillartopBlock::new);
   public static final DeferredBlock<Block> CHISELEDDRIPSTONEPILLARBOTTOM = REGISTRY.register(
      "chiseleddripstonepillarbottom", ChiseleddripstonepillarbottomBlock::new
   );
   public static final DeferredBlock<Block> CHISELEDDRIPSTONEBLOCK = REGISTRY.register("chiseleddripstoneblock", ChiseleddripstoneblockBlock::new);
   public static final DeferredBlock<Block> COFFINBREADSTAGE_2 = REGISTRY.register("coffinbreadstage_2", Coffinbreadstage2Block::new);
   public static final DeferredBlock<Block> COFFINBREADSTAGE_3 = REGISTRY.register("coffinbreadstage_3", Coffinbreadstage3Block::new);
   public static final DeferredBlock<Block> COFFINBREADSTAGE_4 = REGISTRY.register("coffinbreadstage_4", Coffinbreadstage4Block::new);
   public static final DeferredBlock<Block> COFFINBROAD = REGISTRY.register("coffinbroad", CoffinbroadBlock::new);
   public static final DeferredBlock<Block> ALTARNOM = REGISTRY.register("altarnom", AltarnomBlock::new);
   public static final DeferredBlock<Block> ALTARACTIVE = REGISTRY.register("altaractive", AltaractiveBlock::new);
   public static final DeferredBlock<Block> BASALTECHESTE = REGISTRY.register("basaltecheste", BasaltechesteBlock::new);
   public static final DeferredBlock<Block> SOMNOLENCESPAWNS = REGISTRY.register("somnolencespawns", SomnolencespawnsBlock::new);
   public static final DeferredBlock<Block> INDUCERSTONE = REGISTRY.register("inducerstone", InducerstoneBlock::new);
   public static final DeferredBlock<Block> DEEPSLATEINDUCER = REGISTRY.register("deepslateinducer", DeepslateinducerBlock::new);
   public static final DeferredBlock<Block> OAKINDUCER = REGISTRY.register("oakinducer", OakinducerBlock::new);
   public static final DeferredBlock<Block> DARKOAKINDUCER = REGISTRY.register("darkoakinducer", DarkoakinducerBlock::new);
   public static final DeferredBlock<Block> INDUCERSTONEINACTIVE = REGISTRY.register("inducerstoneinactive", InducerstoneinactiveBlock::new);
   public static final DeferredBlock<Block> DEEPSLATEINDUCERINACTIVE = REGISTRY.register("deepslateinducerinactive", DeepslateinducerinactiveBlock::new);
   public static final DeferredBlock<Block> OAKINDUCERINACTIVE = REGISTRY.register("oakinducerinactive", OakinducerinactiveBlock::new);
   public static final DeferredBlock<Block> DARKOAKINDUCERINACTIVE = REGISTRY.register("darkoakinducerinactive", DarkoakinducerinactiveBlock::new);
   public static final DeferredBlock<Block> SPURCEINDUCER = REGISTRY.register("spurceinducer", SpurceinducerBlock::new);
   public static final DeferredBlock<Block> CHERRYBLOSSOMINDUCER = REGISTRY.register("cherryblossominducer", CherryblossominducerBlock::new);
   public static final DeferredBlock<Block> JUNGLEINDUCER = REGISTRY.register("jungleinducer", JungleinducerBlock::new);
   public static final DeferredBlock<Block> BIRCHINDUCER = REGISTRY.register("birchinducer", BirchinducerBlock::new);
   public static final DeferredBlock<Block> SAVANNAINDUCER = REGISTRY.register("savannainducer", SavannainducerBlock::new);
   public static final DeferredBlock<Block> MANGROVEINDUCER = REGISTRY.register("mangroveinducer", MangroveinducerBlock::new);
}
