modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/TwelveIterations/Balm/issues"
[[mods]]
modId="balm"
version="21.0.65"
displayName="Balm"
displayURL="https://mods.twelveiterations.com/"
logoFile="balm.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''Abstraction Layer (but not really) for Blay's multiplatform mods'''
[[mixins]]
config = "balm.mixins.json"
[[mixins]]
config = "balm.neoforge.mixins.json"
[[dependencies.balm]]
modId="neoforge"
type="required"
versionRange="[21.0.82-beta,)"
ordering="NONE"
side="BOTH"
[[dependencies.balm]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"
