package de.markusbordihn.modsoptimizer.config;

import com.google.gson.JsonObject;
import de.markusbordihn.modsoptimizer.Constants;
import de.markusbordihn.modsoptimizer.data.ModFileData;
import de.markusbordihn.modsoptimizer.thirdparty.toml4j.Toml;
import de.markusbordihn.modsoptimizer.thirdparty.toml4j.TomlWriter;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.Map.Entry;

public class ModsDatabaseConfig {
   public static final Path CONFIG_PATH = Paths.get("").toAbsolutePath().resolve("config").resolve("mods_optimizer");
   public static final String ALLOW_REMOTE_DATABASE = "allowRemoteDatabase";
   public static final String DEBUG_ENABLED = "debugEnabled";
   public static final String DEBUG_FORCE_SIDE = "debugForceSide";
   public static final String CONFIG_FILE_NAME = "config.toml";
   private static final Map<String, String> modsMap = new HashMap<>();
   private static boolean allowRemoteDatabase = true;
   private static boolean debugEnabled = false;
   private static String debugForceSide = "default";

   protected ModsDatabaseConfig() {
   }

   public static String getConfigFileName() {
      return "config.toml";
   }

   public static Map<String, String> getConfig() {
      return modsMap;
   }

   public static boolean isDebugEnabled() {
      return debugEnabled;
   }

   public static String getDebugForceSide() {
      return debugForceSide;
   }

   public static boolean containsMod(String modId) {
      return modsMap.containsKey(modId);
   }

   public static ModFileData.ModEnvironment getModEnvironment(String modId) {
      String modType = modsMap.get(modId);
      if ("client".equals(modType)) {
         return ModFileData.ModEnvironment.CLIENT;
      } else {
         return "server".equals(modType) ? ModFileData.ModEnvironment.SERVER : ModFileData.ModEnvironment.BOTH;
      }
   }

   public static String cleanTomlFileWithWarnings(File file) throws IOException {
      Set<String> seenKeys = new HashSet<>();
      StringBuilder cleanedToml = new StringBuilder();
      int lineNumber = 0;

      for (String line : Files.readAllLines(file.toPath(), StandardCharsets.UTF_8)) {
         lineNumber++;
         String trimmed = line.trim();
         if (!trimmed.startsWith("#") && trimmed.contains("=")) {
            String[] keyValue = trimmed.split("=", 2);
            if (keyValue.length < 2) {
               cleanedToml.append(line).append("\n");
            } else {
               String key = keyValue[0].trim();
               if (seenKeys.contains(key)) {
                  Constants.LOG
                     .warn("⚠ Duplicate key '{}' found on line {} in config file {}. This entry was ignored.", new Object[]{key, lineNumber, file.getName()});
               } else {
                  seenKeys.add(key);
                  cleanedToml.append(line).append("\n");
               }
            }
         } else {
            cleanedToml.append(line).append("\n");
         }
      }

      return cleanedToml.toString();
   }

   private static void readConfigFile(File file) {
      if (file == null) {
         file = getConfigFile();
      }

      if (file != null && file.exists() && file.canWrite() && file.canRead()) {
         Constants.LOG.info("Loading Mods Database Config File from {}", file);

         try {
            String cleanedToml = cleanTomlFileWithWarnings(file);
            Map<String, Object> config = new Toml().read(cleanedToml).toMap();
            if (config.containsKey("Database")
               && config.get("Database") instanceof Map<?, ?> database
               && database.get("allowRemoteDatabase") instanceof String stringValue) {
               allowRemoteDatabase = Boolean.parseBoolean(stringValue);
            }

            if (config.containsKey("Debug") && config.get("Debug") instanceof Map<?, ?> debugMap) {
               if (debugMap.get("debugEnabled") instanceof String stringValue) {
                  debugEnabled = Boolean.parseBoolean(stringValue);
               }

               if (debugMap.get("debugForceSide") instanceof String stringValue) {
                  debugForceSide = stringValue;
               }
            }
         } catch (Exception var8) {
            Constants.LOG.error("There was an error, loading the config file {}:", file, var8);
         }
      } else {
         Constants.LOG.error("⚠ Unable to load config file {}!", file);
      }
   }

   private static void appendFileHeader(StringBuilder stringBuilder) {
      stringBuilder.append("# This file was auto-generated by ")
         .append("Mods Optimizer")
         .append("\n")
         .append("# Last update: ")
         .append(LocalDateTime.now())
         .append("\n");
   }

   private static File createConfigFile(File file) {
      Constants.LOG.info("Creating Mods Database Config File under {}", file);
      StringBuilder textContent = new StringBuilder();
      appendFileHeader(textContent);
      OutputStream outputStream = new ByteArrayOutputStream();
      TomlWriter tomlWriter = new TomlWriter.Builder().build();
      Map<String, String> databaseOptions = new HashMap<>();
      databaseOptions.put("allowRemoteDatabase", allowRemoteDatabase ? "true" : "false");

      try {
         tomlWriter.write(databaseOptions, outputStream);
         textContent.append("\n[Database]\n").append(outputStream);
      } catch (Exception var9) {
         Constants.LOG.error("There was an error, adding the database options to the config file {}:", file, var9);
         return null;
      }

      Map<String, String> debugOptions = new HashMap<>();
      debugOptions.put("debugEnabled", debugEnabled ? "true" : "false");
      debugOptions.put("debugForceSide", debugForceSide);
      outputStream = new ByteArrayOutputStream();

      try {
         tomlWriter.write(debugOptions, outputStream);
         textContent.append("\n[Debug]\n").append(outputStream);
      } catch (Exception var8) {
         Constants.LOG.error("There was an error, adding the debug options to the config file {}:", file, var8);
         return null;
      }

      try {
         Files.writeString(file.toPath(), textContent, StandardOpenOption.CREATE_NEW);
         return file;
      } catch (Exception var7) {
         Constants.LOG.error("There was an error, writing the config file to {}:", file, var7);
         return null;
      }
   }

   public static File getConfigFile() {
      Path path = getConfigDirectory();
      return path != null ? path.resolve(getConfigFileName()).toFile() : null;
   }

   private static Path getConfigDirectory() {
      Path resultPath = null;

      try {
         resultPath = Files.createDirectories(CONFIG_PATH);
      } catch (Exception var2) {
         Constants.LOG.error("There was an error, creating the config directory {}:", CONFIG_PATH, var2);
      }

      return resultPath;
   }

   static {
      File configFile = getConfigFile();
      if (configFile == null || !configFile.exists()) {
         configFile = createConfigFile(configFile);
      }

      readConfigFile(configFile);
      if (allowRemoteDatabase) {
         ModsDatabaseUpdater.updateFromRemoteIfNeeded();
      }

      JsonObject json = ModsDatabaseUpdater.getModsDatabase();
      modsMap.putAll(ModsDatabaseUpdater.getSortedModDatabaseMap(json));
      JsonObject overrideJson = ModsDatabaseUpdater.getModsDatabaseOverride();
      Set<String> overrideKeys = ModsDatabaseUpdater.getSortedModDatabaseSet(overrideJson);
      if (!overrideKeys.isEmpty()) {
         Map<String, String> overrides = ModsDatabaseUpdater.getSortedModDatabaseMap(overrideJson);

         for (Entry<String, String> entry : overrides.entrySet()) {
            String modId = entry.getKey();
            String newType = entry.getValue();
            String oldType = modsMap.get(modId);
            if (oldType != null && !oldType.equals(newType)) {
               Constants.LOG.info("{} Override: {} changed from {} to {}", new Object[]{"Mods Optimizer", modId, oldType, newType});
            } else if (oldType == null) {
               Constants.LOG.info("{} Override: {} set to {}", new Object[]{"Mods Optimizer", modId, newType});
            }
         }

         modsMap.putAll(overrides);
      }

      Constants.LOG
         .info(
            "{} Mods Database Config File loaded with {} mods client: {}, server: {}, default: {}{}",
            new Object[]{
               "Mods Optimizer",
               modsMap.size(),
               modsMap.values().stream().filter(modType -> modType.equals("client")).count(),
               modsMap.values().stream().filter(modType -> modType.equals("server")).count(),
               modsMap.values().stream().filter(modType -> modType.equals("default")).count(),
               overrideKeys.isEmpty() ? "." : " (" + overrideKeys.size() + " overrides)."
            }
         );
   }
}
