modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

logoFile="roofslogo.png"
[[mods]]
modId="mcwroofs"
version="2.3.2"
displayName="Macaw's Roofs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-roofs"
updateJSONURL="https://raw.githubusercontent.com/sketchmacaw/macawsmods/master/roofs.json"
credits=""
authors="Sketch Macaw & Sketch Peachy"
description="Build roofs, awnings, rain gutters and more!"
