package de.cristelknight.cristellib;

import com.google.gson.JsonElement;
import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import de.cristelknight.cristellib.config.ConfigType;
import de.cristelknight.cristellib.data.codec.StructureSetData;
import de.cristelknight.cristellib.util.FileHelper;
import de.cristelknight.cristellib.util.JsonHelper;
import de.cristelknight.cristellib.util.runtimepack.RuntimePackUtil;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Map.Entry;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.packs.PackType;

public abstract class StructureConfig {
   public static final Codec<StructureConfig> CODEC = RecordCodecBuilder.create(
      builder -> builder.group(
            Codec.STRING.fieldOf("name").forGetter(config -> FileHelper.fileName(config.getPath())),
            Codec.STRING.fieldOf("path").forGetter(config -> String.valueOf(config.path.getParent())),
            Codec.STRING.optionalFieldOf("header", "").forGetter(config -> config.header),
            ConfigType.CODEC.fieldOf("config_type").forGetter(StructureConfig::getType),
            Codec.unboundedMap(Codec.STRING, Codec.STRING).optionalFieldOf("comments", new HashMap()).forGetter(config -> config.comments),
            Codec.list(StructureSetData.CODEC).fieldOf("structure_sets").forGetter(config -> config.structureSetHolders)
         )
         .apply(
            builder,
            (n, p, h, configType, c, s) -> (StructureConfig)(configType == ConfigType.TOGGLE
               ? new StructureConfigToggle(n, p, h, c, s)
               : new StructureConfigPlacement(n, p, h, c, s))
         )
   );
   private static final Set<ResourceLocation> modifiedSets = new HashSet<>();
   private final Path path;
   private String header = "";
   private Map<String, String> comments;
   private final List<StructureSetData> structureSetHolders;
   private String defaultNamespace = "";
   private boolean isAutoGenerated = false;

   StructureConfig(Path path, String header, Map<String, String> comments, List<StructureSetData> structureSetHolders) {
      this.path = path;
      if (header != null && !header.isEmpty()) {
         this.setHeader(header);
      }

      this.comments = comments;
      this.structureSetHolders = structureSetHolders;
      if (!this.structureSetHolders.isEmpty()) {
         this.setDefaultNamespace();
      }
   }

   void addSet(StructureSetData set) {
      this.structureSetHolders.add(set);
   }

   public static void addSetsToRuntimePack(Collection<StructureConfig> configs) {
      CristelLib.CONFIG_PACK.clear(PackType.SERVER_DATA);
      modifiedSets.clear();
      configs.forEach(StructureConfig::applyToRuntimePack);
   }

   private void applyToRuntimePack() {
      this.readConfig(false);
      this.checkForError();
      this.structureSetHolders.forEach(holder -> holder.sets().forEach(setLocation -> {
         String modId = holder.modId();
         boolean differsFromDefault = this.addChanges(modId, setLocation);
         if (differsFromDefault) {
            modifiedSets.add(setLocation);
         } else if (!modifiedSets.contains(setLocation)) {
            CristelLib.CONFIG_PACK.removeStructureSet(setLocation);
         }
      }));
   }

   public abstract boolean addChanges(String var1, ResourceLocation var2);

   public static JsonElement getStructureSet(ResourceLocation location, String modId) {
      ResourceLocation structureLocation = RuntimePackUtil.getLocationForStructureSet(location);
      return (JsonElement)(CristelLib.CONFIG_PACK.hasData(structureLocation)
         ? CristelLib.CONFIG_PACK.getResourceAsJson(PackType.SERVER_DATA, structureLocation)
         : JsonHelper.getSetElement(location, modId));
   }

   private void checkForError() {
      Set<ResourceLocation> setsToCheck = this.getConfigKeys();
      boolean error = false;

      for (StructureSetData data : this.structureSetHolders) {
         List<ResourceLocation> newlyReadSets = data.sets();
         if (!setsToCheck.containsAll(newlyReadSets)) {
            error = true;
            ArrayList<ResourceLocation> missing = new ArrayList<>(newlyReadSets);
            missing.removeAll(setsToCheck);
            Constants.LOG.error("Structure sets are missing from config: {}", missing);
         }
      }

      if (error) {
         this.resetConfigs();
         String name = FileHelper.fileName(this.path);
         FileHelper.renameFile(this.path, name + "-had-error");
         this.writeConfig(true);
         this.readConfig(true);
      }
   }

   public abstract void writeConfig(boolean var1);

   public abstract void readConfig(boolean var1);

   public static StructureConfig create(Path path, ConfigType type) {
      return (StructureConfig)(type == ConfigType.TOGGLE ? new StructureConfigToggle(path) : new StructureConfigPlacement(path));
   }

   public static StructureConfig create(Path path, String name, ConfigType type) {
      Path fullPath = path.resolve(name + ".json5");
      return create(fullPath, type);
   }

   public static StructureConfig createWithDefaultConfigPath(String subPath, String name, ConfigType type) {
      Path fullPath = PlatformHelper.getConfigDirectory().resolve(subPath).resolve(name + ".json5");
      return create(fullPath, type);
   }

   public static StructureConfig createWithDefaultConfigPath(String name, ConfigType type) {
      Path fullPath = PlatformHelper.getConfigDirectory().resolve(name + ".json5");
      return create(fullPath, type);
   }

   public void setComments(Map<String, String> comments) {
      this.comments = comments;
   }

   public void setHeader(String header) {
      this.header = header;
   }

   public String getHeader() {
      return this.header;
   }

   public Map<String, String> getComments() {
      return this.comments;
   }

   public Path getPath() {
      return this.path;
   }

   public abstract ConfigType getType();

   public ResourceLocation toDefaultId(String id) {
      if (id.contains(":")) {
         return ResourceLocation.parse(id);
      } else {
         return this.defaultNamespace.equals("minecraft")
            ? ResourceLocation.withDefaultNamespace(id)
            : ResourceLocation.fromNamespaceAndPath(this.defaultNamespace, id);
      }
   }

   public String toDefaultString(ResourceLocation id) {
      return id.getNamespace().equals(this.defaultNamespace) ? id.getPath() : id.toString();
   }

   public void setDefaultNamespace() {
      Map<String, Integer> namespaceCounts = new HashMap<>();

      for (StructureSetData data : this.structureSetHolders) {
         for (ResourceLocation set : data.sets()) {
            namespaceCounts.merge(set.getNamespace(), 1, Integer::sum);
         }
      }

      if (namespaceCounts.isEmpty()) {
         throw new RuntimeException("No namespaces found in config with path: " + this.getPath() + " :(((");
      } else {
         this.defaultNamespace = namespaceCounts.entrySet()
            .stream()
            .max(Entry.comparingByValue())
            .map(Entry::getKey)
            .orElseThrow(() -> new RuntimeException("Could not determine default namespace :((("));
      }
   }

   public boolean setsNotEmpty() {
      return !this.structureSetHolders.isEmpty();
   }

   public boolean isAutoGenerated() {
      return this.isAutoGenerated;
   }

   public void setAutoGenerated() {
      this.isAutoGenerated = true;
      this.setHeader("Automatically generated by Cristel Lib");
   }

   public abstract Set<ResourceLocation> getConfigKeys();

   public abstract void resetConfigs();
}
